//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeTableHost {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimeTableHost.ExceptionsResource", typeof(ExceptionsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ظرفیت پر شده است..
        /// </summary>
        public static string _101 {
            get {
                return ResourceManager.GetString("_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمانبندی یافت نشد..
        /// </summary>
        public static string _102 {
            get {
                return ResourceManager.GetString("_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقویم یافت نشد..
        /// </summary>
        public static string _103 {
            get {
                return ResourceManager.GetString("_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تعریف زمانبندی برای روزهای غیر کاری وجود ندارد..
        /// </summary>
        public static string _104 {
            get {
                return ResourceManager.GetString("_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تعریف مانبندی برای خارج از تایم کاری وجود ندارد..
        /// </summary>
        public static string _105 {
            get {
                return ResourceManager.GetString("_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای رزرو باید 2 ساعت قبل اقدام کنید..
        /// </summary>
        public static string _106 {
            get {
                return ResourceManager.GetString("_106", resourceCulture);
            }
        }
    }
}
